# ShipLint Pro — Example Workflow
# Add to your repo at: .github/workflows/shiplint.yml

name: ShipLint

on:
  pull_request:
    branches: [main, develop]
    paths:
      - '**/*.swift'
      - '**/*.m'
      - '**/*.h'
      - '**/*.plist'
      - '**/*.pbxproj'
      - '**/*.xcworkspace/**'
      - '**/*.xcodeproj/**'
      - '**/*.entitlements'
      - '**/*.storyboard'
      - '**/*.xib'

permissions:
  contents: read
  pull-requests: write   # Required for PR comments

jobs:
  shiplint:
    name: ShipLint Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ShipLint
        uses: Signal26AI/ShipLint/action@v1
        with:
          # Auto-detects Xcode project. Set explicitly if needed:
          # project-path: 'MyApp.xcodeproj'
          severity-threshold: 'critical'   # Fail on critical only
          comment: 'true'                  # Post results to PR

---
# Strict mode — fail on medium and above

name: ShipLint (Strict)

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  shiplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Signal26AI/ShipLint/action@v1
        with:
          severity-threshold: 'medium'
          comment: 'true'

---
# SARIF output for GitHub Security tab

name: ShipLint (Security Tab)

on:
  pull_request:
  push:
    branches: [main]

permissions:
  security-events: write
  contents: read
  pull-requests: write

jobs:
  shiplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ShipLint
        id: shiplint
        uses: Signal26AI/ShipLint/action@v1
        with:
          format: 'sarif'
          severity-threshold: 'critical'
          comment: 'true'

      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: shiplint-results.sarif

---
# Monorepo with explicit project path

name: ShipLint (Monorepo)

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ['apps/iOS/MyApp.xcodeproj', 'apps/watchOS/Watch.xcodeproj']
    steps:
      - uses: actions/checkout@v4
      - uses: Signal26AI/ShipLint/action@v1
        with:
          project-path: ${{ matrix.project }}
          severity-threshold: 'high'
