# ReviewShield GitHub Action - Example Workflow
# 
# Add this file to your repo at: .github/workflows/reviewshield.yml

name: ReviewShield

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]

jobs:
  scan:
    name: Scan for App Store Review Issues
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run ReviewShield
        uses: reviewshield/action@v1
        with:
          path: '.'
          format: 'text'
          fail-on-error: 'true'

---
# Alternative: SARIF output for GitHub Security tab

name: ReviewShield (Security Tab)

on:
  pull_request:
  push:
    branches: [main]

jobs:
  scan:
    name: ReviewShield Security Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # Required for uploading SARIF
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run ReviewShield
        id: reviewshield
        uses: reviewshield/action@v1
        with:
          path: '.'
          format: 'sarif'
          fail-on-error: 'false'  # Don't fail, let Security tab show results
      
      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reviewshield-results.sarif

---
# Alternative: Monorepo with multiple iOS projects

name: ReviewShield (Monorepo)

on:
  pull_request:

jobs:
  scan:
    name: Scan iOS Projects
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [apps/ios-app, apps/watchos-app]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Scan ${{ matrix.project }}
        uses: reviewshield/action@v1
        with:
          path: ${{ matrix.project }}
          fail-on-error: 'true'

---
# Alternative: Custom rule selection

name: ReviewShield (Custom Rules)

on:
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run ReviewShield (privacy rules only)
        uses: reviewshield/action@v1
        with:
          path: '.'
          rules: 'missing-camera-purpose,missing-location-purpose,att-tracking-mismatch'
      
      # Or exclude specific rules
      - name: Run ReviewShield (exclude low-priority)
        uses: reviewshield/action@v1
        with:
          path: '.'
          exclude: 'ats-exception-without-justification'
