# ShipLint GitHub Action - Example Workflow
# 
# Add this file to your repo at: .github/workflows/shiplint.yml

name: ShipLint

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]

jobs:
  scan:
    name: Scan for App Store Review Issues
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run ShipLint
        uses: Signal26AI/ShipLint/action@v1
        with:
          path: '.'
          format: 'text'
          fail-on-error: 'true'

---
# Alternative: SARIF output for GitHub Security tab

name: ShipLint (Security Tab)

on:
  pull_request:
  push:
    branches: [main]

jobs:
  scan:
    name: ShipLint Security Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # Required for uploading SARIF
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run ShipLint
        id: shiplint
        uses: Signal26AI/ShipLint/action@v1
        with:
          path: '.'
          format: 'sarif'
          fail-on-error: 'false'  # Don't fail, let Security tab show results
      
      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: shiplint-results.sarif

---
# Alternative: Monorepo with multiple iOS projects

name: ShipLint (Monorepo)

on:
  pull_request:

jobs:
  scan:
    name: Scan iOS Projects
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [apps/ios-app, apps/watchos-app]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Scan ${{ matrix.project }}
        uses: Signal26AI/ShipLint/action@v1
        with:
          path: ${{ matrix.project }}
          fail-on-error: 'true'

---
# Alternative: Custom rule selection

name: ShipLint (Custom Rules)

on:
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run ShipLint (privacy rules only)
        uses: Signal26AI/ShipLint/action@v1
        with:
          path: '.'
          rules: 'privacy-001-missing-camera-purpose,privacy-002-missing-location-purpose,privacy-003-att-tracking-mismatch'
      
      # Or exclude specific rules
      - name: Run ShipLint (exclude low-priority)
        uses: Signal26AI/ShipLint/action@v1
        with:
          path: '.'
          exclude: 'config-001-ats-exception-without-justification'
